server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

chain:
  ip: 45.113.233.149
  port: 6738
  username: multichainrpc
  password: 6vSwnHN2Ndy8qFXVyHneNiZidyFRimzEVhacnqUhY2nZ
  chainName: ImmunoBlock